-- RENAMING COLUMN NAMES
SP_RENAME 'dbo.airline_passenger_satisfaction.[Type of Travel]','TYPE_OF_TRAVEL','COLUMN'
GO
SP_RENAME 'dbo.airline_passenger_satisfaction.[Flight Distance]','FLIGHT_DISTANCE','COLUMN'
GO
SP_RENAME 'dbo.airline_passenger_satisfaction.[Departure Delay]','DEPARTURE_DELAY','COLUMN'
GO
SP_RENAME 'dbo.airline_passenger_satisfaction.[Arrival Delay]','ARRIVAL_DELAY','COLUMN'
GO
SP_RENAME 'dbo.airline_passenger_satisfaction.[Departure and Arrival Time Convenience]','DEPARTURE_AND_ARRIVAL_TIME','COLUMN'
GO
SP_RENAME 'dbo.airline_passenger_satisfaction.[Ease of Online Booking]','EASE_OF_ONLINE_BOOKING','COLUMN'
GO
SP_RENAME'dbo.airline_passenger_satisfaction.[Check-in Service]','CHECK_IN_SERVICE','COLUMN'
GO
SP_RENAME 'dbo.airline_passenger_satisfaction.[Online Boarding]','ONLINE_BOARDING','COLUMN'
GO
SP_RENAME 'dbo.airline_passenger_satisfaction.[Gate Location]','GATE_LOCATION','COLUMN'
GO
SP_RENAME 'dbo.airline_passenger_satisfaction.[On-board Service]','ON-BOARD_SERVICE','COLUMN'
GO
SP_RENAME 'dbo.airline_passenger_satisfaction.[Seat Comfort]','SEAT_COMFORT','COLUMN'
GO
SP_RENAME 'dbo.airline_passenger_satisfaction.[Leg Room Service]','LEG_ROOM_SERVICE','COLUMN'
GO
SP_RENAME 'dbo.airline_passenger_satisfaction.[Cleanliness]','CLEANLINESS','COLUMN'
GO
SP_RENAME 'dbo.airline_passenger_satisfaction.[Food and Drink]','FOOD_AND_DRINK','COLUMN'
GO
SP_RENAME 'dbo.airline_passenger_satisfaction.[In-flight Service]','IN-FLIGHT_SERVICE','COLUMN'
GO
SP_RENAME 'dbo.airline_passenger_satisfaction.[In-flight Wifi Service]','IN-FLIGHT_WIFI_SERVICE','COLUMN'
GO
SP_RENAME 'dbo.airline_passenger_satisfaction.[In-flight Entertainment]','IN-FLIGHT_ENTERTAINMENT','COLUMN'
GO
SP_RENAME 'dbo.airline_passenger_satisfaction.[Baggage Handling]','BAGGAGE_HANDLING','COLUMN'
GO
SP_RENAME 'dbo.airline_passenger_satisfaction.[Satisfaction]','SATIFACTION','COLUMN'
GO
SP_RENAME 'dbo.airline_passenger_satisfaction.Gender', 'GENDER','COLUMN'
GO
SP_RENAME 'dbo.airline_passenger_satisfaction.Age', 'AGE','COLUMN'
GO
SP_RENAME 'dbo.airline_passenger_satisfaction.Class', 'CLASS','COLUMN'
GO

-- CHANGING DATA TYPES TO SUIT COLUMNS FOR PROPER EXPLORATION

ALTER TABLE [dbo].[airline_passenger_satisfaction]
ALTER COLUMN AGE INT
ALTER TABLE [dbo].[airline_passenger_satisfaction]
ALTER COLUMN [FLIGHT_DISTANCE] INT
ALTER TABLE [dbo].[airline_passenger_satisfaction]
ALTER COLUMN [DEPARTURE_DELAY] INT
ALTER TABLE [dbo].[airline_passenger_satisfaction]
ALTER COLUMN [ARRIVAL_DELAY] INT
ALTER TABLE [dbo].[airline_passenger_satisfaction]
ALTER COLUMN [DEPARTURE_AND_ARRIVAL_TIME] INT
ALTER TABLE [dbo].[airline_passenger_satisfaction]
ALTER COLUMN [EASE_OF_ONLINE_BOOKING] INT
ALTER TABLE [dbo].[airline_passenger_satisfaction]
ALTER COLUMN [CHECK_IN_SERVICE] INT
ALTER TABLE [dbo].[airline_passenger_satisfaction]
ALTER COLUMN [ONLINE_BOARDING] INT
ALTER TABLE [dbo].[airline_passenger_satisfaction]
ALTER COLUMN [GATE_LOCATION] INT
ALTER TABLE [dbo].[airline_passenger_satisfaction]
ALTER COLUMN [ON-BOARD_SERVICE] INT
ALTER TABLE [dbo].[airline_passenger_satisfaction]
ALTER COLUMN [SEAT_COMFORT] INT
ALTER TABLE [dbo].[airline_passenger_satisfaction]
ALTER COLUMN [LEG_ROOM_SERVICE] INT
ALTER TABLE [dbo].[airline_passenger_satisfaction]
ALTER COLUMN [CLEANLINESS] INT
ALTER TABLE [dbo].[airline_passenger_satisfaction]
ALTER COLUMN[FOOD_AND_DRINK] INT
ALTER TABLE [dbo].[airline_passenger_satisfaction]
ALTER COLUMN [IN-FLIGHT_SERVICE] INT
ALTER TABLE [dbo].[airline_passenger_satisfaction]
ALTER COLUMN [IN-FLIGHT_ENTERTAINMENT] INT
ALTER TABLE [dbo].[airline_passenger_satisfaction]
ALTER COLUMN [BAGGAGE_HANDLING] INT

--CHECKING FOR DUPLICATES IN DATA
WITH DUPLICATE_CHECK_CTE AS (SELECT [GENDER],
	[AGE],
	[CUSTOMER_TYPE],
	[TYPE_OF_TRAVEL],
	[CLASS], 
	ROW_NUMBER() OVER (PARTITION BY	ID,
									GENDER, 
									AGE,
									CUSTOMER_TYPE,
									TYPE_OF_TRAVEL,
									CLASS,
									[FLIGHT_DISTANCE],
									[DEPARTURE_DELAY],
									[ARRIVAL_DELAY],
									[DEPARTURE_AND_ARRIVAL_TIME] ORDER BY ID) AS ROW_COUNT
FROM airline_passenger_satisfaction)
SELECT *
FROM DUPLICATE_CHECK_CTE
WHERE ROW_COUNT >1;

-- Which percentage of airline passengers are satisfied? Does it vary by customer type? What about type of travel?

---FINDING PERECENTAGE OF PASSENGERS SATISFIED
 WITH CTE1 AS (
	SELECT SATIFACTION, 
		   COUNT(SATIFACTION) AS COUNT_OF_SATIFACTION
	FROM airline_passenger_satisfaction
	GROUP BY SATIFACTION),
 CTE2 AS(
	SELECT  SUM(COUNT_OF_SATIFACTION) TOTAL_SATIFACTION
 FROM CTE1
		)
 SELECT CTE1.SATIFACTION, 
 CTE1.COUNT_OF_SATIFACTION,
 CTE2.TOTAL_SATIFACTION, 
 ROUND (CAST(COUNT_OF_SATIFACTION AS float)/TOTAL_SATIFACTION * 100,2) PERCENTAGE_SATISFIED
 FROM CTE1
 JOIN CTE2
 ON COUNT_OF_SATIFACTION = COUNT_OF_SATIFACTION;

 --FINDING PERECNTAGE OF PASSENGERS SATISIFIED BY TYPE OF TRAVEL

WITH TRAVEL_CTE AS (
	SELECT	TYPE_OF_TRAVEL, 
			SATIFACTION, 
			COUNT(SATIFACTION) COUNT_OF_SATIFACTION_BY_TRAVEL_TYPE
FROM MSSQLTutortial.DBO.airline_passenger_satisfaction
GROUP BY TYPE_OF_TRAVEL, SATIFACTION
),
	TRAVEL_CTE2 AS(
	SELECT	SUM(COUNT_OF_SATIFACTION_BY_TRAVEL_TYPE) TOTAL_SATISFACTION
FROM TRAVEL_CTE)

SELECT	TRAVEL_CTE.TYPE_OF_TRAVEL, 
		TRAVEL_CTE.SATIFACTION, 
		TRAVEL_CTE.COUNT_OF_SATIFACTION_BY_TRAVEL_TYPE, 
		ROUND(CAST(TRAVEL_CTE.COUNT_OF_SATIFACTION_BY_TRAVEL_TYPE AS float)/TRAVEL_CTE2.TOTAL_SATISFACTION *100,2) PERCENTAGE_SATISFIED_BY_TYPE_OF_TRAVEL
FROM TRAVEL_CTE
JOIN TRAVEL_CTE2
ON TYPE_OF_TRAVEL = TYPE_OF_TRAVEL
ORDER BY TYPE_OF_TRAVEL;

 --FINDING PERECNTAGE OF PASSENGERS SATISIFIED BY CUSTOMER_TYPE
 WITH CUSTOMER_TYPE_CTE AS (
	SELECT	CUSTOMER_TYPE, 
			SATIFACTION, 
			COUNT(SATIFACTION) COUNT_OF_SATIFACTION_BY_CUSTOMER_TYPE
FROM MSSQLTutortial.DBO.airline_passenger_satisfaction
GROUP BY CUSTOMER_TYPE, SATIFACTION
),
CUSTOMER_TYPE_CTE2 AS(
	SELECT	SUM(COUNT_OF_SATIFACTION_BY_CUSTOMER_TYPE) TOTAL_SATISFACTION
FROM CUSTOMER_TYPE_CTE)

SELECT	CUSTOMER_TYPE_CTE.CUSTOMER_TYPE, 
		CUSTOMER_TYPE_CTE.SATIFACTION, 
		CUSTOMER_TYPE_CTE.COUNT_OF_SATIFACTION_BY_CUSTOMER_TYPE, 
		ROUND(CAST(CUSTOMER_TYPE_CTE.COUNT_OF_SATIFACTION_BY_CUSTOMER_TYPE AS float)/CUSTOMER_TYPE_CTE2.TOTAL_SATISFACTION *100,2) PERCENTAGE_SATISFIED_BY_CUSTOMER_TYPE
FROM CUSTOMER_TYPE_CTE
JOIN CUSTOMER_TYPE_CTE2
ON CUSTOMER_TYPE= CUSTOMER_TYPE
ORDER BY CUSTOMER_TYPE;

-- TOTAL BREAKDOWN OF SATISFIED CUSTOMERS 
WITH TOTAL_SATISFACTION_CTE AS	(SELECT	CUSTOMER_TYPE,
										TYPE_OF_TRAVEL,
										SATIFACTION,
										COUNT(SATIFACTION) COUNT_OF_SATIFACTION_BY_ALL
								FROM MSSQLTutortial.DBO.airline_passenger_satisfaction
								GROUP BY CUSTOMER_TYPE, SATIFACTION, TYPE_OF_TRAVEL
								),
	TOTAL_SATISFACTION_CTE2 AS (SELECT SUM(COUNT_OF_SATIFACTION_BY_ALL) SUM_OF_TOTAL
								FROM TOTAL_SATISFACTION_CTE)
SELECT 	TOTAL_SATISFACTION_CTE.CUSTOMER_TYPE,
		TOTAL_SATISFACTION_CTE.TYPE_OF_TRAVEL,
		TOTAL_SATISFACTION_CTE.SATIFACTION,
		TOTAL_SATISFACTION_CTE.COUNT_OF_SATIFACTION_BY_ALL,
		ROUND(CAST(TOTAL_SATISFACTION_CTE.COUNT_OF_SATIFACTION_BY_ALL AS float)/TOTAL_SATISFACTION_CTE2.SUM_OF_TOTAL *100,2) TOTAL_PERECENTAGE
FROM TOTAL_SATISFACTION_CTE
JOIN TOTAL_SATISFACTION_CTE2
ON SATIFACTION = SATIFACTION
ORDER BY SATIFACTION;

--What is the customer profile for a repeating airline passenger?
-- PERECENTAGE OF CUSTOMERS THAT ARE RETURNING
WITH CUSTOMER_PROFILE_CTE AS (SELECT	[GENDER],
										[AGE],
										[CUSTOMER_TYPE],
										[TYPE_OF_TRAVEL],
										[CLASS], 
										COUNT(CUSTOMER_TYPE) OVER () AS TOTAL_CUSTOMER_COUNT,
										COUNT(CUSTOMER_TYPE) OVER ( PARTITION BY CUSTOMER_TYPE) AS CUSTOMER_TYPE_COUNT
							FROM airline_passenger_satisfaction)
	SELECT DISTINCT 
			CUSTOMER_TYPE, 
			CUSTOMER_TYPE_COUNT,
			TOTAL_CUSTOMER_COUNT, ROUND(CAST(CUSTOMER_TYPE_COUNT AS float)/TOTAL_CUSTOMER_COUNT *100,2) CUSTOMER_TYPE_PERCENTAGE
	FROM CUSTOMER_PROFILE_CTE;


	

-- PROFILE OF RETURNING CUSTOMERS
---- GENDER PROFILE 
WITH GENDER_COUNT_CTE AS (	SELECT GENDER, COUNT (GENDER) GENDER_COUNT
							FROM airline_passenger_satisfaction
							WHERE CUSTOMER_TYPE = 'Returning'
							GROUP BY GENDER
							),
	GENDER_COUNT_CTE2 AS ( SELECT SUM(GENDER_COUNT) GENDER_TOTAL_SUM
							FROM GENDER_COUNT_CTE
							)
	SELECT	GENDER_COUNT_CTE.GENDER, 
			GENDER_COUNT_CTE.GENDER_COUNT,
			ROUND (CAST (GENDER_COUNT AS float)/GENDER_TOTAL_SUM *81.69,2) GENDER_PERECENTAGE_FOR_RETURNING_CUSTOMER
	FROM GENDER_COUNT_CTE
	JOIN GENDER_COUNT_CTE2
	ON GENDER = GENDER;

---- TYPE OF TRAVEL PROFILE
WITH TRAVEL_TYPE_COUNT_CTE AS (	SELECT	TYPE_OF_TRAVEL, 
										COUNT (TYPE_OF_TRAVEL) TYPE_OF_TRAVEL_COUNT
								FROM airline_passenger_satisfaction
								WHERE CUSTOMER_TYPE = 'Returning'
								GROUP BY TYPE_OF_TRAVEL
							),
	TRAVEL_TYPE_COUNT_CTE2 AS ( SELECT SUM( TYPE_OF_TRAVEL_COUNT) TYPE_OF_TRAVEL_TOTAL_SUM
								FROM TRAVEL_TYPE_COUNT_CTE
							)
	SELECT	TRAVEL_TYPE_COUNT_CTE.TYPE_OF_TRAVEL, 
			TRAVEL_TYPE_COUNT_CTE. TYPE_OF_TRAVEL_COUNT, 
			ROUND (CAST ( TYPE_OF_TRAVEL_COUNT AS float)/ TYPE_OF_TRAVEL_TOTAL_SUM *81.69,2) TYPE_OF_TRAVEL_PERECENTAGE_FOR_RETURNING_CUSTOMER
	FROM TRAVEL_TYPE_COUNT_CTE
	JOIN TRAVEL_TYPE_COUNT_CTE2
	ON TYPE_OF_TRAVEL = TYPE_OF_TRAVEL;

---- PROFILE OF CLASS FLOWN BY RETURNING CUSTOMERS
WITH CLASS_COUNT_CTE AS (	SELECT CLASS, COUNT (CLASS) CLASS_COUNT
							FROM airline_passenger_satisfaction
							WHERE CUSTOMER_TYPE = 'Returning'
							GROUP BY CLASS
							),
	CLASS_COUNT_CTE2 AS ( SELECT SUM(CLASS_COUNT) CLASS_TOTAL_SUM
							FROM CLASS_COUNT_CTE
							)
SELECT CLASS_COUNT_CTE.CLASS,
	CLASS_COUNT_CTE.CLASS_COUNT,
	ROUND (CAST (CLASS_COUNT AS float)/CLASS_TOTAL_SUM *81.69,2) CLASS_PERECENTAGE_FOR_RETURNING_CUSTOMER
	FROM CLASS_COUNT_CTE
	JOIN CLASS_COUNT_CTE2
	ON CLASS = CLASS;

---- PROFILE OF AGE FOR RETURNING CUSTOMERS

WITH  AGE_PROFILE_CTE AS (SELECT T1.AGE_GROUP, COUNT(T1.AGE_GROUP) COUNT_OF_AGE_GROUP

						  FROM (					SELECT	AGE,
															CASE 
															WHEN AGE <13 THEN 'CHILD'
															WHEN AGE BETWEEN 13 AND 17 THEN 'TEEN'
															WHEN AGE BETWEEN 18 AND 59 THEN 'ADULT'									
															ELSE 'ELDERLY'
															END AS AGE_GROUP
													FROM airline_passenger_satisfaction
													WHERE CUSTOMER_TYPE= 'Returning'
								) AS T1
						GROUP BY T1.AGE_GROUP      
						),
	AGE_PROFILE_CTE2 AS (SELECT SUM(COUNT_OF_AGE_GROUP) TOTAL_SUM_OF_AGE_GROUP
						 FROM AGE_PROFILE_CTE
						 )

	SELECT *, ROUND(CAST(COUNT_OF_AGE_GROUP AS float)/TOTAL_SUM_OF_AGE_GROUP *81.69,2) PERCENTAGE_AGE_GROUP_FOR_RETURNING
	FROM AGE_PROFILE_CTE
	JOIN AGE_PROFILE_CTE2
	ON AGE_GROUP = AGE_GROUP
	ORDER BY PERCENTAGE_AGE_GROUP_FOR_RETURNING DESC

--Does flight distance affect customer preferences or flight patterns?
---- HOW FLIGHT LENGTH RELATES TO TYPE OF TRAVEL
WITH FLIGHT_DISTANCE_CTE AS (SELECT T1.TYPE_OF_TRAVEL,T1.FLIGHT_LENGTH, COUNT(T1.FLIGHT_LENGTH) COUNT_OF_FLIGHT
							 FROM	(SELECT  TYPE_OF_TRAVEL,
												CASE 
												WHEN FLIGHT_DISTANCE <800 THEN 'SHORT HAUL FLIGHT'
												WHEN FLIGHT_DISTANCE BETWEEN 801 AND 2559 THEN 'MEDIUM HAUL FLIGHT'
												ELSE 'LONG HAUL FLIGHT'
												END AS FLIGHT_LENGTH
												FROM airline_passenger_satisfaction
									)AS T1
							GROUP BY T1.TYPE_OF_TRAVEL,T1.FLIGHT_LENGTH
							),
	FLIGHT_DISTANCE_CTE2 AS ( SELECT FLIGHT_LENGTH, SUM(COUNT_OF_FLIGHT) SUM_OF_TOTAL_FLIGHT_DISTANCE
							  FROM FLIGHT_DISTANCE_CTE
							  GROUP BY FLIGHT_LENGTH
							 )
	SELECT FLIGHT_DISTANCE_CTE.TYPE_OF_TRAVEL, 
		   FLIGHT_DISTANCE_CTE.FLIGHT_LENGTH, 
		   COUNT_OF_FLIGHT, SUM_OF_TOTAL_FLIGHT_DISTANCE, 
		 ROUND(  CAST(COUNT_OF_FLIGHT AS float)/SUM_OF_TOTAL_FLIGHT_DISTANCE*100,2  ) PERCENTAGE_RATIO
	FROM FLIGHT_DISTANCE_CTE
	JOIN FLIGHT_DISTANCE_CTE2
	ON FLIGHT_DISTANCE_CTE.FLIGHT_LENGTH = FLIGHT_DISTANCE_CTE2.FLIGHT_LENGTH
	ORDER BY FLIGHT_LENGTH,TYPE_OF_TRAVEL,PERCENTAGE_RATIO;

---- MOST UTILISED FLIGHT LENGTH FOR EACH TRAVEL CLASS

WITH FLIGHT_CLASS_CTE AS (SELECT T1.CLASS,T1.FLIGHT_LENGTH, COUNT(T1.FLIGHT_LENGTH) COUNT_OF_FLIGHT
							 FROM	(SELECT  CLASS,
												CASE 
												WHEN FLIGHT_DISTANCE <800 THEN 'SHORT HAUL FLIGHT'
												WHEN FLIGHT_DISTANCE BETWEEN 801 AND 2559 THEN 'MEDIUM HAUL FLIGHT'
												ELSE 'LONG HAUL FLIGHT'
												END AS FLIGHT_LENGTH
												FROM airline_passenger_satisfaction
									)AS T1
							GROUP BY T1.CLASS,T1.FLIGHT_LENGTH
							),
	FLIGHT_CLASS_CTE2 AS ( SELECT CLASS, SUM(COUNT_OF_FLIGHT) SUM_OF_TOTAL_FLIGHT_DISTANCE
							  FROM FLIGHT_CLASS_CTE
							  GROUP BY CLASS
							 )
	SELECT FLIGHT_CLASS_CTE.CLASS, 
		   FLIGHT_CLASS_CTE.FLIGHT_LENGTH, 
		   COUNT_OF_FLIGHT, SUM_OF_TOTAL_FLIGHT_DISTANCE, 
		 ROUND(  CAST(COUNT_OF_FLIGHT AS float)/SUM_OF_TOTAL_FLIGHT_DISTANCE*100,2  ) PERCENTAGE_PREFERENCE
	FROM FLIGHT_CLASS_CTE
	JOIN FLIGHT_CLASS_CTE2
	ON FLIGHT_CLASS_CTE.CLASS = FLIGHT_CLASS_CTE2.CLASS
	ORDER BY CLASS,PERCENTAGE_PREFERENCE DESC,FLIGHT_LENGTH;

--------- CLASS PREFERENCE FOR VARIOUS FLIGHT LENGTH
	WITH FLIGHT_CLASS_CTE AS (SELECT T1.CLASS,T1.FLIGHT_LENGTH, COUNT(T1.FLIGHT_LENGTH) COUNT_OF_FLIGHT
							 FROM	(SELECT  CLASS,
												CASE 
												WHEN FLIGHT_DISTANCE <800 THEN 'SHORT HAUL FLIGHT'
												WHEN FLIGHT_DISTANCE BETWEEN 801 AND 2559 THEN 'MEDIUM HAUL FLIGHT'
												ELSE 'LONG HAUL FLIGHT'
												END AS FLIGHT_LENGTH
												FROM airline_passenger_satisfaction
									)AS T1
							GROUP BY T1.CLASS,T1.FLIGHT_LENGTH
							),
	FLIGHT_CLASS_CTE2 AS ( SELECT FLIGHT_LENGTH, SUM(COUNT_OF_FLIGHT) SUM_OF_TOTAL_FLIGHT_DISTANCE
							  FROM FLIGHT_CLASS_CTE
							  GROUP BY FLIGHT_LENGTH
							 )
	SELECT FLIGHT_CLASS_CTE.CLASS, 
		   FLIGHT_CLASS_CTE.FLIGHT_LENGTH, 
		   COUNT_OF_FLIGHT, SUM_OF_TOTAL_FLIGHT_DISTANCE, 
		 ROUND(  CAST(COUNT_OF_FLIGHT AS float)/SUM_OF_TOTAL_FLIGHT_DISTANCE*100,2  ) PERCENTAGE_PREFERENCE
	FROM FLIGHT_CLASS_CTE
	JOIN FLIGHT_CLASS_CTE2
	ON FLIGHT_CLASS_CTE.FLIGHT_LENGTH = FLIGHT_CLASS_CTE2.FLIGHT_LENGTH
	ORDER BY FLIGHT_LENGTH,CLASS,PERCENTAGE_PREFERENCE

	-----
	